# Default values for golang-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

name: my-react

image:
  repository: registry.digitalocean.com/enigmacamp/simple-react
  tag: "13"
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: regcred

service:
  protocol: TCP
  type: ClusterIP
  port: 80

apiUrl:
  host: golang-service
  port: "8888"