apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  annotations:
    configmap.reloader.stakater.com/reload: "{{ .Release.Name }}-config"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-default-conf
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      volumes:
        - name: nginx-default-conf
          configMap:
            name: {{ .Release.Name }}-config
            items:
              - key: default.conf
                path: default.conf
