apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  annotations:
    reloader.stakater.com/auto: 'true'
data:
  PORT: "{{ .Values.service.targetPort }}"
  RESPONSE: "{{ .Values.config.response }}"