# Default values for golang-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

name: my-golang

image:
  repository: registry.digitalocean.com/enigmacamp/simple-go
  tag: "4"
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: regcred

service:
  protocol: TCP
  type: ClusterIP
  port: 8888
  targetPort: 8888

config:
  response: Yoyoyo